### PR TITLE
updated Cargo file with changed piston-related dependency names and repo...

### PR DESCRIPTION
**Pull request by Byron**
...sitories.

Unfortunately, it doesn't yet compile as some other dependencies don't seem to compile with `rustc 1.0.0-dev`. Maybe I am not latest enough as I installed via brew, and didn't try the nightly binary installers yet.

For completeness, I am dropping the issues here - it's not related to snake.rs at all:

``` bash
Compiling gl_common v0.0.3 (https://github.com/bjz/gl-rs#a5be6727)
   Compiling current v0.0.5 (https://github.com/pistondevelopers/current#749a98a3)
   Compiling khronos_api v0.0.5 (https://github.com/bjz/gl-rs#a5be6727)
   Compiling piston-texture v0.0.1
   Compiling khronos_api v0.0.5
   Compiling shader_version v0.0.1 (https://github.com/pistondevelopers/shader_version#71300bf7)
   Compiling piston-texture v0.0.1 (https://github.com/PistonDevelopers/texture#0380876c)
   Compiling rustc-serialize v0.2.8
/Users/byron/.cargo/git/checkouts/current-4c0469929c5bbcc9/master/src/lib.rs:10:5: 10:21 error: unresolved import `std::any::TypeId`. There is no `TypeId` in `std::any`
/Users/byron/.cargo/git/checkouts/current-4c0469929c5bbcc9/master/src/lib.rs:10 use std::any::TypeId;
                                                                                    ^~~~~~~~~~~~~~~~
error: aborting due to previous error
   Compiling clock_ticks v0.0.2 (https://github.com/tomaka/clock_ticks#75347002)
   Compiling pkg-config v0.1.5
   Compiling read_color v0.0.2 (https://github.com/PistonDevelopers/read_color#568723fb)
   Compiling gcc v0.1.5
   Compiling vecmath v0.0.2 (https://github.com/PistonDevelopers/vecmath#5ac4d2ec)
   Compiling regex v0.1.10
   Compiling quack v0.0.2 (https://github.com/PistonDevelopers/quack#e12ef316)
/Users/byron/.cargo/git/checkouts/quack-5c2e81a611f5edcd/master/src/lib.rs:20:9: 20:10 error: unexpected token: `<`
/Users/byron/.cargo/git/checkouts/quack-5c2e81a611f5edcd/master/src/lib.rs:20         <(U, T) as GetFrom>::get_from(obj.borrow().deref())
                                                                                      ^
   Compiling bitflags v0.1.0
   Compiling interpolation v0.0.1 (https://github.com/PistonDevelopers/interpolation#81b572b9)
Build failed, waiting for other jobs to finish...
Could not compile `current`.
```

### CODE REVIEW

**Comment by Arcterus** [comment]
Can you check to see if the problems with the dependencies are resolved with the latest nightly?

**Comment by Byron** [comment]
Here are the results on your latest master:
```bash
➜  rust-snake git:(master) ✗ rustc --version
rustc 1.0.0-nightly (29bd9a06e 2015-01-20 23:03:09 +0000)
➜  rust-snake git:(master) ✗ cargo --version
cargo 0.0.1-pre-nightly (2422edc 2015-01-19 07:28:44 +0000)
➜  rust-snake git:(master) ✗ cargo clean
➜  rust-snake git:(master) ✗ cargo build
    Updating git repository `https://github.com/PistonDevelopers/sdl2_game_window`
    Updating git repository `https://github.com/PistonDevelopers/opengl_graphics`
    Updating git repository `https://github.com/PistonDevelopers/rust-graphics`
no matching package named `sdl2_game_window` found (required by `snake`)
location searched: https://github.com/PistonDevelopers/sdl2_game_window
version required: *
```
When trying to compile with my branch, I noticed that one of the dependencies didn't want to build, even after `cargo clean`. So I ran `cargo update` (excuse my verbosity, these are my very first steps with rust.

```bash
    Updating git repository `https://github.com/PistonDevelopers/opengl_graphics`
    Updating git repository `https://github.com/PistonDevelopers/piston`
    Updating git repository `https://github.com/PistonDevelopers/graphics`
    Updating git repository `https://github.com/PistonDevelopers/sdl2_game_window`
    Updating git repository `https://github.com/PistonDevelopers/freetype-rs.git`
    Updating git repository `https://github.com/bjz/gl-rs`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/pistondevelopers/shader_version`
    Updating git repository `https://github.com/pistondevelopers/texture`
    Updating git repository `https://github.com/pistondevelopers/image`
    Updating git repository `https://github.com/PistonDevelopers/freetype-sys`
    Updating git repository `https://github.com/PistonDevelopers/interpolation`
    Updating git repository `https://github.com/PistonDevelopers/read_color`
    Updating git repository `https://github.com/PistonDevelopers/vecmath`
    Updating git repository `https://github.com/PistonDevelopers/quack`
    Updating git repository `https://github.com/rust-lang/num`
    Updating git repository `https://github.com/pistondevelopers/event`
    Updating git repository `https://github.com/AngryLawyer/rust-sdl2`
    Updating git repository `https://github.com/pistondevelopers/ai_behavior`
    Updating git repository `https://github.com/pistondevelopers/sdl2_window`
    Updating git repository `https://github.com/pistondevelopers/fps_counter`
    Updating git repository `https://github.com/pistondevelopers/drag_controller`
    Updating git repository `https://github.com/pistondevelopers/current`
    Updating git repository `https://github.com/pistondevelopers/select_color`
    Updating git repository `https://github.com/pistondevelopers/cam`
    Updating git repository `https://github.com/pistondevelopers/input`
    Updating git repository `https://github.com/pistondevelopers/window`
    Updating git repository `https://github.com/PistonDevelopers/event_loop`
    Updating git repository `https://github.com/tomaka/clock_ticks`
```
And this is what I see when trying to compile on my master:

```bash
[...]
               	                       ^~~~
src/snake.rs:14:14: 14:18 error: unresolved import `piston::Game`. There is no `Game` in `piston`
src/snake.rs:14 use piston::{Game, GameIteratorSettings, GameWindowSettings, KeyReleaseArgs, RenderArgs};
                             ^~~~
src/snake.rs:14:20: 14:40 error: unresolved import `piston::GameIteratorSettings`. There is no `GameIteratorSettings` in `piston`
src/snake.rs:14 use piston::{Game, GameIteratorSettings, GameWindowSettings, KeyReleaseArgs, RenderArgs};
                                   ^~~~~~~~~~~~~~~~~~~~
src/snake.rs:14:42: 14:60 error: unresolved import `piston::GameWindowSettings`. There is no `GameWindowSettings` in `piston`
src/snake.rs:14 use piston::{Game, GameIteratorSettings, GameWindowSettings, KeyReleaseArgs, RenderArgs};
                                                         ^~~~~~~~~~~~~~~~~~
src/snake.rs:14:62: 14:76 error: unresolved import `piston::KeyReleaseArgs`. There is no `KeyReleaseArgs` in `piston`
src/snake.rs:14 use piston::{Game, GameIteratorSettings, GameWindowSettings, KeyReleaseArgs, RenderArgs};
                                                                             ^~~~~~~~~~~~~~
src/snake.rs:15:5: 15:32 error: unresolved import `sdl2_window::GameWindowSDL2`. There is no `GameWindowSDL2` in `sdl2_window`
src/snake.rs:15 use sdl2_window::GameWindowSDL2;
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 5 previous errors
Could not compile `snake`.
```

I tried to fix it, but realized that piston apparently changed so much that I have trouble finding the required symbols.

**Comment by Byron** [comment]
Maybe the problem can be alleviated if you upload your Cargo.lock file, which in theory should contain information about all the versions you used back in the days when it was compiling ?
As I said, I have no actual experience, but have read about that file :).

**Comment by Arcterus** [comment]
I'm not sure if the `Cargo.lock` file existed when I last updated this program, but I definitely don't have one at the moment. :/

I've just started trying to update `game-of-life`, so I guess I'll just port the changes over here when I'm done.

**Comment by Byron** [comment]
Awsome, great to hear ! I have forked it with the intend of hacking and realized it had the same troubles as snake. Therefore I shall follow your master closely.
And thanks for looking into this, it's much like pioneering work :).
